version: "3.9"
services:
  discovery_node:
    build: .
    expose:
      - 80
    volumes:
      - .:/app
    command: ruby server.rb
    stdin_open: true
    tty: true
  full_node:
    build: .
    expose:
      - 80
    volumes:
      - .:/app
    command: ruby client.rb
    stdin_open: true
    tty: true
    depends_on:
      - discovery_node

