version: "3.9"

services:
  fluent_bit:
    image: fluent/fluent-bit
    volumes:
      - ./../monitoring/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./../monitoring/fluent-bit-stdout.conf:/fluent-bit/etc/fluent-bit-stdout.conf
      - ./../monitoring/fluent-bit-service.conf:/fluent-bit/etc/fluent-bit-service.conf
      - ./../monitoring/custom_parsers.conf:/fluent-bit/etc/custom_parsers.conf
      - ./../logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/fluentd/log/containers
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      bc:

  discovery_node:
    build:
      context: $PWD/blockchain/
      dockerfile: ../docker/Dockerfile
    expose:
      - 80
    volumes:
      - $PWD/blockchain:/app
    depends_on:
      - fluent_bit
    # command: bash
    command: ruby discovery_node.rb
    stdin_open: true
    tty: true
    networks:
      bc:
    logging:
      driver: fluentd
      options:
        tag: discovery_node
  full_node:
    build:
      context: $PWD/blockchain/
      dockerfile: ../docker/Dockerfile
    expose:
      - 80
    volumes:
      - $PWD/blockchain:/app
    # command: bash
    command: ruby full_node.rb
    networks:
      bc:
    stdin_open: true
    tty: true
    depends_on:
      - discovery_node
      - fluent_bit
      - queue
    logging:
      driver: fluentd
      options:
        tag: full_node
  queue:
    image: rabbitmq:3.9.10-management
    expose:
      - 5672
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'
    networks:
      bc:
    stdin_open: true
    tty: true

volumes:
  rabbitmq_data:

networks:
  bc:
    external: true
