version: "3.7"

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - "3100"
    networks:
      bc:
      bc-monitoring:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - bc-monitoring
    volumes:
      - ./../monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./../monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana-image-renderer
    expose:
      - "8081"
    environment:
      ENABLE_METRICS: "true"
    networks:
      - bc-monitoring

networks:
  bc:
    external: true
  bc-monitoring:
    external: true
