{
 "title": "Blockchain network",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Tokens in network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of blocks created by peer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({message_name=\"new_block\"} | json [24h])) by (message_properties_from)"
    }
   ]
  },
  {
   "title": "Number of tokens sent within the network",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(({message_name=\"new_block\"} | json | unwrap message_properties_tokens [24h])))"
    }
   ]
  },
  {
   "title": "Number of transactions received by peer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({message_name=\"new_block\"} | json [24h])) by (message_properties_to)"
    }
   ]
  },
  {
   "title": "Number of tokens send by peers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({message_name=\"new_block\"} | json | unwrap message_properties_tokens [1s])) by (message_properties_from)"
    }
   ]
  },
  {
   "title": "Number of tokens received by peers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({message_name=\"new_block\"} | json | unwrap message_properties_tokens [1s])) by (message_properties_to)"
    }
   ]
  },
  { "title": "Requests' times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Request time per peer (MIN)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time({message_name=\"request_time\"} | json | unwrap message_properties_time [1m])) by (container_name)"
    }
   ]
  },
  {
   "title": "Request time per peer (AVG)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time({message_name=\"request_time\"} | json | unwrap message_properties_time [1m])) by (container_name)"
    }
   ]
  },
  {
   "title": "Request time per peer (MAX)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time({message_name=\"request_time\"} | json | unwrap message_properties_time [1m])) by (container_name)"
    }
   ]
  },
  {
   "title": "Sum of requests times per container",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate({message_name=\"request_time\"} | json | unwrap message_properties_time [1m]))"
    }
   ]
  },
  {
   "title": "Requests count per peer",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (count_over_time({message_count=\"1\",message_name=\"request_time\"}[1m]))"
    }
   ]
  }
 ]
}