# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activesupport', '~> 6.1'
gem 'bunny', '~> 2.19'
gem 'colorize', '~> 0.8.1'
gem 'dry-initializer', '~> 3.0'
gem 'faraday', '~> 1.3'
gem 'pry'
gem 'rubocop', '~> 1.12'
gem 'sinatra', '~> 2.1'
gem 'thread_safe', '~> 0.3.6'
